#!/bin/bash
# $Id: fetchBuildXPilot5,v 1.7 2004/03/02 05:14:26 dick Exp $
# fetchBuildXPilot5 - a script to suck XPilot5 and fltk from cvs.buckosoft.com
#                     or www.buckosoft.com via rsync
#                     and build all of the pieces for a Un*x installation of
#                     XPilot, a multiplayer gravity war game.
#                     Copyright (C) 2004 by XPilot Team http://www.xpilot.org
#                     Released under GNU General Public License Version 2
#
# Choose where to build xpilot5 from
#set -x
SRCDIR="$HOME/src/xpilot5"
#SRCDIR="/tmp/src/xpilot5"

# Choose where to install xpilot5 to.
TARGETDIR="$HOME/xpilot"

# perhaps you want to set some other options...
#MYCONFIGOPTS="--disable-silent --enable-debug"


# If are root, then install to the standard locations.
if [ `whoami` = root ]; then
	TARGETDIR="/usr/local/xpilot"
fi

# You probably don't want to change this
CVSROOT=":pserver:cvsguest@cvs.buckosoft.com:/Projects/xpilot5"

#######################################################
#######################################################
# Move along folks. Nothing to see below here...
#######################################################
#######################################################

#######################################################
function doHELP ()
{
	echo "fetchBuildXPilot5 [-ch] [-r rev]"
	echo "  -c     = CVS - Fetch from CVS.  The default is to fetch the latest .tgz file"
	echo "  -r rev = Revision - Fetch a specific version.  For CVS use r5_0_0a1 style and .tgz use 5.0.0a1"
	echo "  -l     = List versions available and exit (CVS only)"
	echo "  -h     = Help - this text"
}


#######################################################
DOCVS=0
DOLISTVERSIONS=0
DORELEASE=

while getopts "chlr:" OPT
do
	case $OPT in
		c) DOCVS=1 ;;
		r) DORELEASE=$OPTARG ;;
		l) DOLISTVERSIONS=1 ;;
		h) doHELP ; exit 1 ;;
		*) doHELP ; exit 1 ;;
	esac
done

#######################################################
# Precheck directories
#
if [ ! -d $SRCDIR ];    then mkdir -p $SRCDIR    || exit 1 ; fi
if [ ! -d $TARGETDIR ]; then mkdir -p $TARGETDIR || exit 1 ; fi


#######################################################
# Do we need to login to cvs?
#
if [ $DOCVS = 1 ]; then
	PASS=`grep /Projects/xpilot5 $HOME/.cvspass`
	if [ "x$PASS" = "x" ]; then
		cvs -d $CVSROOT login || exit 1
	fi
fi

#######################################################
# List versions?
#
if [ $DOLISTVERSIONS = 1 ]; then
	echo "Listing available cvs versions..."
	cd $SRCDIR
	cvs -d $CVSROOT rlog xpilot5/.cvsignore |grep "r5" |grep ": "|cut -f2 | cut -f1 -d':'
	exit 2
fi

#######################################################
# find out the latest version using rsync
#
cd $SRCDIR
if [ "$DOCVS" = "0" -a "x$DORELEASE" = "x" ]; then
	#rm -f versionKey
	echo "Determining latest xpilot version"
	rsync --progress -u www.buckosoft.com::xpilotctl/versionKey .
	if [ $? != 0 ]; then
		echo "rsync error fetching versionKey"
		exit 1
	fi
	if [ ! -f versionKey ]; then
		echo "versionKey file not fetched"
		exit 1
	fi
fi

#######################################################
# fetch fltk
#
cd $SRCDIR
REBUILDFLTK=Y
if [ $DOCVS = 1 ]; then
	FLTKSRCDIR="fltk"
	if [ ! -d fltk ]; then
		cvs -d $CVSROOT co fltk || exit 1
	else
		cd fltk || exit 1
		echo "### Updating fltk"
		NEEDFLTK=`cvs -n update |grep "^U "`
		if [ "x$NEEDFLTK" = x ]; then
			REBUILDFLTK=N
			echo "### Rebuild of fltk not required"
		else
			cvs update
		fi
		cd ..
	fi
else
	FLTKVERFILE=`grep FLTKNIX versionKey | cut -f2 -d '='`
	FLTKSRCDIR=`basename $FLTKVERFILE .tgz`
	echo "Fetching $FLTKVERFILE via rsync"
	rsync --progress -u www.buckosoft.com::xpilot5/$FLTKVERFILE .
	tar -xvzf $FLTKVERFILE
fi

#######################################################
# fetch xpilot5
#
REBUILDXP5=Y
if [ $DOCVS = 1 ]; then
	XP5SRCDIR="xpilot5"
	if [ ! -d xpilot5 ]; then
		cvs -d $CVSROOT co xpilot5 || exit 1
	else
		cd xpilot5 || exit1
		echo "### Updating xpilot5"
		NEEDFLTK=`cvs -n update |grep "^U "`
		if [ "x$NEEDFLTK" = x ]; then
			REBUILDXP5=N
			echo "### Rebuild of xpilot5 not required"
		else
			cvs update
		fi
		cd ..
	fi
else
	XP5VERFILE=`grep XP5NIX versionKey | cut -f2 -d '='`
	XP5SRCDIR=`basename $XP5VERFILE .tgz`
	echo "Fetching $XP5VERFILE via rsync"
	rsync --progress -u www.buckosoft.com::xpilot5/$XP5VERFILE .
	tar -xvzf $XP5VERFILE
fi
#######################################################
# check for serverpassword.
# This may require human intervention, so do it early.
#
cd $SRCDIR/$XP5SRCDIR
if [ ! -f .serverpassword ]; then
	echo "### Server password not set, calling ./config.password to set it"
	echo "###"
	echo ""
	./config.password
	echo ""
	echo "OK, continuing with the build"
fi

#######################################################
# go build libpng
#
cd $SRCDIR/$FLTKSRCDIR/libpng
echo "### building libpng"

if [ ! -f Makefile ]; then
	SYS=`uname -s`
	case $SYS in
		Linux)		cp scripts/makefile.linux Makefile ;;
		*)			echo "#######################################################"
					echo "I can't determine which png makefile to use"
					echo -n "Press y to send \"`uname -a`\" to bucko to help fix this problem [y]"
					read ANS
					if [ "x$ANS" = "xy" -o "x$ANS" = "xY" -o "x$ANS" = "x" ]; then
						uname -a | mail -s "fetchbuildXPilot5 failure" bucko5@xpilot.org || exit 1
						echo "OK, mail has been sent to bucko.  In the meantime, you can figure out"
					else
						echo "OK, no mail.  You are going to have to figure out"
					fi
					echo "which one of the makefiles in scripts to use, and copy that to Makefile"
					echo "in this directory.  Like this: cp scripts/makefile.linux Makefile"
					echo "Here's a list of files in scripts..."
					ls scripts
					echo "I'll give you a shell and wait.  Type exit when you're done."
					/bin/bash
					if [ ! -f Makefile ]; then
						echo "OK, so you didn't copy a makefile.  I have to give up."
						exit 2
					fi
					;;
	esac

fi

if [ ! -f Makefile ]; then
	echo "There is no usable Makefile for libpng.  I give up."
	echo 2
fi

echo "##########################################################"
echo "#                     making libpng                      #"
echo "##########################################################"
make || exit 1
cp libpng.a ../lib

if [ ! -f ../png.h ]; then
	cp png.h ..
	cp pngconf.h ..
fi


echo "##########################################################"
echo "#                   configuring fltk                     #"
echo "##########################################################"
cd ..
if [ $REBUILDFLTK = Y ]; then
	echo "./configure"
	./configure || exit 1
	make clean || exit 1
else
	echo "fltk configure and clean NOT required."
fi

echo "##########################################################"
echo "#                      making fltk                       #"
echo "##########################################################"
make || exit 1

echo "##########################################################"
echo "#                  configuring xpilot5                   #"
echo "##########################################################"
cd $SRCDIR/$XP5SRCDIR
if [ $REBUILDXP5 = Y ]; then
   #CONFIGOPTS="--prefix=$TARGETDIR --enable-fltkdir=$SRCDIR/fltk"
	CONFIGOPTS="--prefix=$TARGETDIR --enable-fltkdir=$SRCDIR/$FLTKSRCDIR $MYCONFIGOPTS"
	echo "./configure $CONFIGOPTS"
	./configure $CONFIGOPTS || exit 1
	make clean || exit 1
else
	echo "xp5 configure and clean NOT required."
fi

echo "##########################################################"
echo "#                     making xpilot5                     #"
echo "##########################################################"
make || exit 1

echo "##########################################################"
echo "#                   installing xpilot5                   #"
echo "##########################################################"
make install
