// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "StdAfx.h"
#include "XPFileChooser.h"

inline void XPFileChooser::cb_window_i(Fl_Double_Window*, void*) {
  fileName->value("");
fileList->deselect();
Fl::remove_timeout((Fl_Timeout_Handler)previewCB, this);
window->hide();
}
void XPFileChooser::cb_window(Fl_Double_Window* o, void* v) {
  ((XPFileChooser*)(o->user_data()))->cb_window_i(o,v);
}

inline void XPFileChooser::cb_showChoice_i(Fl_Choice*, void*) {
  showChoiceCB();
}
void XPFileChooser::cb_showChoice(Fl_Choice* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_showChoice_i(o,v);
}

inline void XPFileChooser::cb_favoritesButton_i(Fl_Menu_Button*, void*) {
  favoritesButtonCB();
}
void XPFileChooser::cb_favoritesButton(Fl_Menu_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_favoritesButton_i(o,v);
}

inline void XPFileChooser::cb_newButton_i(Fl_Button*, void*) {
  newdir();
}
void XPFileChooser::cb_newButton(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_newButton_i(o,v);
}

inline void XPFileChooser::cb__i(Fl_Tile*, void*) {
  update_preview();
}
void XPFileChooser::cb_(Fl_Tile* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb__i(o,v);
}

inline void XPFileChooser::cb_fileList_i(Fl_File_Browser*, void*) {
  fileListCB();
}
void XPFileChooser::cb_fileList(Fl_File_Browser* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_fileList_i(o,v);
}

inline void XPFileChooser::cb_previewButton_i(Fl_Check_Button*, void*) {
  preview(previewButton->value());
}
void XPFileChooser::cb_previewButton(Fl_Check_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->parent()->user_data()))->cb_previewButton_i(o,v);
}

inline void XPFileChooser::cb_wildMapButton_i(Fl_Check_Button*, void*) {
  wildMap(wildMapButton->value());
}
void XPFileChooser::cb_wildMapButton(Fl_Check_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->parent()->user_data()))->cb_wildMapButton_i(o,v);
}

inline void XPFileChooser::cb_fileName_i(Fl_File_Input*, void*) {
  fileNameCB();
}
void XPFileChooser::cb_fileName(Fl_File_Input* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_fileName_i(o,v);
}

inline void XPFileChooser::cb_okButton_i(Fl_Return_Button*, void*) {
  // Do any callback that is registered...
if (callback_)
  (*callback_)(this, data_);

window->hide();
}
void XPFileChooser::cb_okButton(Fl_Return_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->parent()->user_data()))->cb_okButton_i(o,v);
}

inline void XPFileChooser::cb_Cancel_i(Fl_Button*, void*) {
  fileName->value("");
fileList->deselect();
Fl::remove_timeout((Fl_Timeout_Handler)previewCB, this);
window->hide();
}
void XPFileChooser::cb_Cancel(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->parent()->user_data()))->cb_Cancel_i(o,v);
}

inline void XPFileChooser::cb_wildNumber_i(Fl_Value_Input*, void*) {
  wildNumberCB();
}
void XPFileChooser::cb_wildNumber(Fl_Value_Input* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_wildNumber_i(o,v);
}

inline void XPFileChooser::cb_wildRandomButton_i(Fl_Button*, void*) {
  wildRandomCB();
}
void XPFileChooser::cb_wildRandomButton(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_wildRandomButton_i(o,v);
}

inline void XPFileChooser::cb_wildSlider_i(Fl_Slider*, void*) {
  wildSliderCB();
}
void XPFileChooser::cb_wildSlider(Fl_Slider* o, void* v) {
  ((XPFileChooser*)(o->parent()->parent()->user_data()))->cb_wildSlider_i(o,v);
}

inline void XPFileChooser::cb_favList_i(Fl_File_Browser*, void*) {
  favoritesCB(favList);
}
void XPFileChooser::cb_favList(Fl_File_Browser* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb_favList_i(o,v);
}

inline void XPFileChooser::cb_favUpButton_i(Fl_Button*, void*) {
  favoritesCB(favUpButton);
}
void XPFileChooser::cb_favUpButton(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb_favUpButton_i(o,v);
}

inline void XPFileChooser::cb_favDeleteButton_i(Fl_Button*, void*) {
  favoritesCB(favDeleteButton);
}
void XPFileChooser::cb_favDeleteButton(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb_favDeleteButton_i(o,v);
}

inline void XPFileChooser::cb_favDownButton_i(Fl_Button*, void*) {
  favoritesCB(favDownButton);
}
void XPFileChooser::cb_favDownButton(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb_favDownButton_i(o,v);
}

inline void XPFileChooser::cb_favCancelButton_i(Fl_Button*, void*) {
  favWindow->hide();
}
void XPFileChooser::cb_favCancelButton(Fl_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb_favCancelButton_i(o,v);
}

inline void XPFileChooser::cb_favOkButton_i(Fl_Return_Button*, void*) {
  favoritesCB(favOkButton);
}
void XPFileChooser::cb_favOkButton(Fl_Return_Button* o, void* v) {
  ((XPFileChooser*)(o->parent()->user_data()))->cb_favOkButton_i(o,v);
}

XPFileChooser::XPFileChooser(const char *d, const char *p, int t, const char *title) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = window = new Fl_Double_Window(507, 407, "Choose File");
    w = o;
    o->callback((Fl_Callback*)cb_window, (void*)(this));
    { Fl_Group* o = new Fl_Group(52, 10, 448, 25);
      { Fl_Choice* o = showChoice = new Fl_Choice(52, 10, 249, 25, "Show:");
        o->down_box(FL_BORDER_BOX);
        o->callback((Fl_Callback*)cb_showChoice);
        Fl_Group::current()->resizable(o);
        showChoice->label(show_label);
      }
      { Fl_Menu_Button* o = favoritesButton = new Fl_Menu_Button(309, 10, 155, 25, "Favorites");
        o->down_box(FL_BORDER_BOX);
        o->callback((Fl_Callback*)cb_favoritesButton);
        o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        favoritesButton->label(favorites_label);
      }
      { Fl_Button* o = newButton = new Fl_Button(474, 10, 25, 25);
        o->tooltip("Create a new directory.");
        o->labelsize(8);
        o->callback((Fl_Callback*)cb_newButton);
      }
      o->end();
    }
    { Fl_Tile* o = new Fl_Tile(10, 45, 471, 225);
      o->callback((Fl_Callback*)cb_);
      { Fl_File_Browser* o = fileList = new Fl_File_Browser(10, 45, 295, 225);
        o->type(2);
        o->callback((Fl_Callback*)cb_fileList);
      }
      { Fl_Box* o = previewBox = new Fl_Box(305, 45, 175, 225, "?");
        o->box(FL_DOWN_BOX);
        o->labelsize(100);
        o->align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE);
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = new Fl_Group(0, 275, 480, 125);
      { Fl_Group* o = new Fl_Group(10, 275, 470, 40);
        { Fl_Check_Button* o = previewButton = new Fl_Check_Button(10, 275, 170, 20, "Preview");
          o->down_box(FL_DOWN_BOX);
          o->value(1);
          o->shortcut(0x80070);
          o->callback((Fl_Callback*)cb_previewButton);
          previewButton->label(preview_label);
        }
        { Fl_Box* o = new Fl_Box(10, 275, 210, 20);
          Fl_Group::current()->resizable(o);
        }
        { Fl_Check_Button* o = wildMapButton = new Fl_Check_Button(10, 295, 170, 20, "&Wild map");
          o->tooltip("Select a random map generated by the computer");
          o->down_box(FL_DOWN_BOX);
          o->shortcut(0x80077);
          o->callback((Fl_Callback*)cb_wildMapButton);
          wildMapButton->label(wildMap_label);
        }
        { Fl_Box* o = mapInfo = new Fl_Box(220, 275, 260, 20);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        o->end();
      }
      { Fl_File_Input* o = fileName = new Fl_File_Input(115, 325, 365, 35);
        o->callback((Fl_Callback*)cb_fileName);
        o->when(FL_WHEN_ENTER_KEY);
        fileName->when(FL_WHEN_CHANGED | FL_WHEN_ENTER_KEY_ALWAYS);
      }
      { Fl_Box* o = fileNameLabel = new Fl_Box(10, 335, 105, 25, "Filename:");
        o->box(FL_NO_BOX);
        o->color(FL_BACKGROUND_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(FL_BLACK);
        o->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
        o->when(FL_WHEN_RELEASE);
        fileNameLabel->label(filename_label);
      }
      { Fl_Group* o = new Fl_Group(5, 375, 470, 25);
        { Fl_Return_Button* o = okButton = new Fl_Return_Button(295, 375, 85, 25, "OK");
          o->callback((Fl_Callback*)cb_okButton);
          okButton->label(fl_ok);
        }
        { Fl_Button* o = new Fl_Button(390, 375, 85, 25, "Cancel");
          o->callback((Fl_Callback*)cb_Cancel);
          o->label(fl_cancel);
        }
        { Fl_Box* o = new Fl_Box(5, 375, 300, 25);
          Fl_Group::current()->resizable(o);
        }
        o->end();
      }
      { Fl_Box* o = wildLabel = new Fl_Box(8, 335, 105, 25, "Wild #");
        o->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
      }
      { Fl_Value_Input* o = wildNumber = new Fl_Value_Input(115, 335, 125, 25);
        o->tooltip("Type in a number to be used to seed the Wild Map generator.");
        o->maximum(1e+009);
        o->callback((Fl_Callback*)cb_wildNumber);
      }
      { Fl_Button* o = wildRandomButton = new Fl_Button(390, 335, 90, 25, "&Random");
        o->tooltip("Select a Random seed to make the Random map.");
        o->shortcut(0x80072);
        o->callback((Fl_Callback*)cb_wildRandomButton);
      }
      { Fl_Slider* o = wildSlider = new Fl_Slider(240, 335, 150, 25);
        o->type(5);
        o->maximum(1e+009);
        o->step(1);
        o->callback((Fl_Callback*)cb_wildSlider);
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    if (title) window->label(title);
    o->set_modal();
    o->end();
  }
  { Fl_Double_Window* o = favWindow = new Fl_Double_Window(355, 150, "Manage Favorites");
    w = o;
    o->user_data((void*)(this));
    { Fl_File_Browser* o = favList = new Fl_File_Browser(10, 10, 300, 95);
      o->type(2);
      o->callback((Fl_Callback*)cb_favList);
    }
    { Fl_Button* o = favUpButton = new Fl_Button(320, 10, 25, 25, "@8>");
      o->callback((Fl_Callback*)cb_favUpButton);
    }
    { Fl_Button* o = favDeleteButton = new Fl_Button(320, 45, 25, 25, "X");
      o->labelfont(1);
      o->callback((Fl_Callback*)cb_favDeleteButton);
    }
    { Fl_Button* o = favDownButton = new Fl_Button(320, 80, 25, 25, "@2>");
      o->callback((Fl_Callback*)cb_favDownButton);
    }
    { Fl_Button* o = favCancelButton = new Fl_Button(270, 115, 75, 25, "Cancel");
      o->callback((Fl_Callback*)cb_favCancelButton);
      favCancelButton->label(fl_cancel);
    }
    { Fl_Return_Button* o = favOkButton = new Fl_Return_Button(185, 115, 75, 25, "OK");
      o->callback((Fl_Callback*)cb_favOkButton);
      favOkButton->label(fl_ok);
    }
    favWindow->label(manage_favorites_label);
    o->set_modal();
    o->end();
  }
  callback_ = 0;
data_ = 0;
directory_[0] = 0;
window->size_range(window->w(), window->h(), Fl::w(), Fl::h());
type(t);
filter(p);
update_favorites();
wildMap(0);
value(d);
type(t);
int e;
prefs_.get("preview", e, 1);
preview(e);
}

XPFileChooser::~XPFileChooser() {
  Fl::remove_timeout((Fl_Timeout_Handler)previewCB, this);
delete window;
delete favWindow;
}

void XPFileChooser::callback(void (*cb)(XPFileChooser *, void *), void *d ) {
  callback_ = cb;
data_     = d;
}

void XPFileChooser::color(Fl_Color c) {
  fileList->color(c);
}

Fl_Color XPFileChooser::color() {
  return (fileList->color());
}

char * XPFileChooser::directory() {
  return directory_;
}

const char * XPFileChooser::filter() {
  return (fileList->filter());
}

int XPFileChooser::filter_value() {
  return showChoice->value();
}

void XPFileChooser::filter_value(int f) {
  showChoice->value(f);
showChoiceCB();
}

void XPFileChooser::hide() {
  window->hide();
}

void XPFileChooser::iconsize(uchar s) {
  fileList->iconsize(s);
}

uchar XPFileChooser::iconsize() {
  return (fileList->iconsize());
}

void XPFileChooser::label(const char *l) {
  window->label(l);
}

const char * XPFileChooser::label() {
  return (window->label());
}

void XPFileChooser::show() {
  window->hotspot(fileList);
window->show();
fileName->take_focus();
}

int XPFileChooser::shown() {
  return window->shown();
}

void XPFileChooser::textcolor(Fl_Color c) {
  fileList->textcolor(c);
}

Fl_Color XPFileChooser::textcolor() {
  return (fileList->textcolor());
}

void XPFileChooser::textfont(uchar f) {
  fileList->textfont(f);
}

uchar XPFileChooser::textfont() {
  return (fileList->textfont());
}

void XPFileChooser::textsize(uchar s) {
  fileList->textsize(s);
}

uchar XPFileChooser::textsize() {
  return (fileList->textsize());
}

void XPFileChooser::type(int t) {
  type_ = t;
if (t & MULTI)
  fileList->type(FL_MULTI_BROWSER);
else
  fileList->type(FL_HOLD_BROWSER);
if (t & CREATE)
  newButton->activate();
else
  newButton->deactivate();
if (t & DIRECTORY)
  fileList->filetype(Fl_File_Browser::DIRECTORIES);
else
  fileList->filetype(Fl_File_Browser::FILES);
}

int XPFileChooser::type() {
  return (type_);
}

int XPFileChooser::visible() {
  return window->visible();
}
