; $Id: getpw.ini,v 1.4 2004/08/01 02:10:08 dick Exp $
; getpw.ini - Query the user for a password during installation
;
; This ini file is called by InstallOptions.dll (part of NSIS)
;
; $Log: getpw.ini,v $
; Revision 1.4  2004/08/01 02:10:08  dick
; Update to nsis 2.0
;
; Revision 1.3  2004/02/29 06:17:36  dick
; Say xpilot5, not ++
;
; Revision 1.2  2002/07/23 17:43:50  dick
; whitespace
;
; Revision 1.1  2002/07/22 07:23:48  dick
; Set the server password during Windows installation.
;

[Settings]
NumFields=2
Title=XPilot5 Setup: Choose a server password
BackEnabled=1
CancelButtonText=Cancel
NextButtonText=Next >
BackButtonText=< Back

[Field 1]
Type=Label
Text=You must choose a password for your server.  If you are not going to ever configure this server from another computer or give the password to your buddies, then you can choose something good and random
State=0
Left=0
Right=258
Top=0
Bottom=65

[Field 2]
Type=Text
Text=MyPassword
Left=0
Right=262
Top=70
Bottom=83

